### ISSUE TITLE
Black wallpaper on Ubuntu 20.04

### ISSUE THREAD

**Issue by dm7500** [adi1090x/dynamic-wallpaper#11]
When I run it on Ubuntu 20.04, I get only a black wallpaper, and no error in the command line. All it tell's me is that it's `Running...`.

I made sure to install all dependencies as described in the Readme, and followed the instructions. Running stock Gnome 3.36.1.

Am I missing something?

**Comment by dm7500** [comment]
Using [this fork](https://github.com/corfeur12/dynamic-wallpaper) solved my issue. Not sure what the difference was though.

**Comment by chuahou** [comment]
If it works with a fork but not this, would you consider reopening the issue since it is still a bug in this original repo?
