### ISSUE TITLE
Crontab Suggestion

### ISSUE THREAD

**Issue by AlricRahl** [adi1090x/dynamic-wallpaper#15]
Hello, a cronjob newbie here

I couldn't use the script directly at cronjob. The problem was the limited environment that crontab runs on. It took me some time to figure out which environment variables are needed to be defined in crontab, so I thought writing it here might be helpful for others. Here are the variables that I had to define in the crontab for the cronjob to work:

- SHELL
- DESKTOP_SESSION
- XDG_RUNTIME_DIR
- XDG_DATA_DIRS
- DBUS_SESSION_BUS_ADDRESS

You can find what values your environment has by typing `env` in your terminal or check each variable via `$VARIABLE_NAME` one by one.  Maybe writing a small section in the readme about this might be nice as well. Hope this helps someone!

**Comment by BerentM** [comment]
Great idea, that would be helpful. Without your tip i didn't manage to force crontab to work with dwall.
I would add info about DISPLAY=:0 too, for at least xfce users.

**Comment by adi1090x** [comment]
Thanks, I'll add it to readme.

**Comment by rbreaves** [comment]
@AlricRahl Did you set the crontab under sudo or something? I'd have assumed that the needed env variables would be accessible as long as your had added the cron under your own user?

**Comment by AlricRahl** [comment]
@rbreaves I just used the regular crontab, tho since it runs with an environment with minimum amount of variables, I think these were not defined in that minimum environment, at least in my case.

**Comment by dasco597** [comment]
note for any sway users: I also had to include the SWAYSOCK variable to get this to work. In my case it was SWAYSOCK=/run/user/1000/sway-ipc.1000.425.sock

**Comment by Neules** [comment]
> note for any sway users: I also had to include the SWAYSOCK variable to get this to work. In my case it was SWAYSOCK=/run/user/1000/sway-ipc.1000.425.sock

@dasco597 Could you paste your crontab rule please? I'm running Sway as well

**Comment by dasco597** [comment]
@Neules not sure if it's all needed I was trying a few different ideas

0 * * * * env DISPLAY=:0.0 SHELL=/bin/zsh DESKTOP_SESSION=sway DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" XDG_RUNTIME_DIR=/run/user/1000 SHELL=/bin/zsh TERM=alacritty PATH=$PATH:/usr/bin SWAYSOCK=/run/user/1000/sway-ipc.1000.425.sock /usr/bin/dwall -s desert > ~/.config/cron-msg.cron 2>&1

**Comment by Neules** [comment]
@dasco597 There it is!! Perfect!! Thank you!! it worked now, don't know which env var was. I added `SHELL`, `TERM`, `XDG_RUNTIME_DIR` and changed `PATH=/usr/local/bin:/usr/bin` to `PATH=$PATH:/usr/bin`.

I'm pasting my cron job for any other Sway user that may be having issues:

`env SHELL=/bin/zsh PATH=$PATH:/usr/bin DISPLAY=:0 TERM=foot SWAYSOCK=/run/user/1000/sway-ipc.1000.1914.sock DESKTOP_SESSION=sway XDG_RUNTIME_DIR=/run/user/1000 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" /usr/bin/dwall -s cliffs`
