### ISSUE TITLE
manjaro kde plasma serious problem ! please help !

### ISSUE THREAD

**Issue by astralgenixx** [adi1090x/dynamic-wallpaper#20]
any of the wallapaper, i mean dynamic wallpaper is not working_i mean changing at all !!
very confused why this happening to kde plasma 

please help !
none of the wallpaper is not changing  ....
i have seen in your tested DE list there are no KDE PLASMA 

![Screenshot_20200505_133327](https://user-images.githubusercontent.com/64389321/81045997-074ebb80-8ed5-11ea-8295-e883bfa68966.png)

*******help*******

**Comment by adi1090x** [comment]
What you mean by **any** wallpaper, is dynamic-wallpaper not working you are you not able to set any kind of wallpaper in your DESKTOP?

**Comment by emptyedge** [comment]
Yes, dynamic wallpapers do not work for me on kde manjaro either. When I install the theme with the dwall -s style command, the wallpaper is set only once, and then remains static. that is, the script sets the desired wallpaper in time only at the time the command is entered, and then it does not work.

**Comment by adi1090x** [comment]
It's actually working, maybe you just terminate it during exiting the terminal, if you want the script to run in background, consider starting it when plasma desktop runs (autostart the script)

**Comment by emptyedge** [comment]
Ok, thanks. I really interrupted him in the terminal. I apologize, I thought that it will start automatically after installation. I think you should notify the user when downloading or installing
