### ISSUE TITLE
XFCE4 - start on boot

### ISSUE THREAD

**Issue by tambow44** [adi1090x/dynamic-wallpaper#22]
Tried all sorts of nonsense re WM autostart (.xinitrc, crontab - yes saw the other suggestion re the env variables).

This is what worked for me:

```
> pwd ; more dwall.desktop
/usr/home/tblakel/.config/autostart
[Desktop Entry]
Hidden=false
Exec=/usr/bin/dwall -s forest &
Name=DWall Autostart
Comment=https://github.com/adi1090x/dynamic-wallpaper
```

I know this works in Arch, and FreeBSD, might be helpful for others to see.

**Comment by adi1090x** [comment]
Thanks, I'll add it to readme.
