### ISSUE TITLE
Nothing happens on Gnome

### ISSUE THREAD

**Issue by adityaarun1** [adi1090x/dynamic-wallpaper#23]
I have `gnome` DE running on Arch Linux over `wayland`. When I run `dwall -s firewatch`, nothing happens (there is no output on the terminal).
![Screenshot from 2020-05-08 17-20-26](https://user-images.githubusercontent.com/6547096/81403090-489ecf80-9150-11ea-91f1-ad5c9f86f83f.png)

**Comment by adi1090x** [comment]
Hmm, I've not tried it on Wayland, i can't say what's wrong here, script seems to work fine, but setter not working i guess...

**Comment by adityaarun1** [comment]
Yep, `gsettings set org.gnome.desktop.background picture-uri` doesn't seem to work for some weird reason.

**Comment by Sergeygithub** [comment]
What about the permissions for the folder with the images?

**Comment by adityaarun1** [comment]
I think the images folder `/usr/share/dynamic-wallpaper/images` and its contents have proper permissions. The permissions for the jpg files are `644` and the directories are `751`.

**Comment by Sergeygithub** [comment]
> I think the images folder `/usr/share/dynamic-wallpaper/images` and its contents have proper permissions. The permissions for the jpg files are `644` and the directories are `751`.

try to set `0755` for the directory

**Comment by adityaarun1** [comment]
Done, it doesn't help! :neutral_face:

**Comment by adityaarun1** [comment]
Finally solved it!

I use miniconda python distribution on my system which ships its own `gsettings`! Simply forcing the script `dwall.sh` to use the system `/usr/bin/gsettings` solves the issue.

Thanks for your support.
