### ISSUE TITLE
Aspect ratio handling

### ISSUE THREAD

**Issue by hixan** [adi1090x/dynamic-wallpaper#24]
When used on monitors with strange aspect ratios (eg ultrawide or portrait) the background gets stretched and looks quite odd. Is there a way to configure behaviour when the aspect ratio of the image does not match the aspect ratio of the display?

**Comment by adi1090x** [comment]
Try feh modes of wallpaper setting, and use accordingly in the script.

**Comment by hixan** [comment]
Why is style an argument for -s and -o? would it make more sense to simply have -o as an optional flag and style as a required positional argument?

**Comment by adi1090x** [comment]
Done.
