### ISSUE TITLE
Not working for xfce4 (galliumOS)

### ISSUE THREAD

**Issue by rbreaves** [adi1090x/dynamic-wallpaper#25]
1. Wallpaper not changing : echo $DESKTOP_SESSION.
    /usr/bin/startxfce4

2. Not working on XFCE 
xfconf-query -c xfce4-desktop -m
```
Start monitoring channel "xfce4-desktop":
set: /backdrop/screen0/monitor0/workspace0/last-image
```

I updated ./test.sh to have screen and monitor set to 0. Re-ran the test and it still failed.

Before updating it I believe this is how it was resolving
```
# screen
xrandr --listactivemonitors | awk -F ' ' 'END {print $1}' | tr -d \:
0
# monitor
xrandr --listactivemonitors | awk -F ' ' 'END {print $2}' | tr -d \*+
eDP-1
```

**Comment by adi1090x** [comment]
You need to add `/usr/bin/startxfce4` in that wallpaper setting line for xfce.

**Comment by rbreaves** [comment]
On xfce I think you need to run this command to get a full list of all possible monitors, 

    xfconf-query -c xfce4-desktop --list

This command for active monitors
    xrandr | grep connected

And just note that eDP-1 tends to be the internal lcd screen of most laptops, so eDP-1 only equals 0, not the eDP-1 entries that may appear in the xfconf-query.
