### ISSUE TITLE
Code repetition

### ISSUE THREAD

**Issue by 6gk** [adi1090x/dynamic-wallpaper#30]
Near line 59, there is a case statement that checks if the OSTYPE is 'linux', but in the end, that statement is useless since you're using the same code for every other OS type.

Suggested change: the case statement is removed and replaced with lines 61-75

**Comment by PPHyperion** [comment]
@GaugeK you can clone this project edit your suggested changes and open a pull request.

**Comment by GaugeK** [comment]
@PPHyperion Good idea.
