### ISSUE TITLE
The sun in firewatch and firewatch2 is going the wrong way

### ISSUE THREAD

**Issue by honze-net** [adi1090x/dynamic-wallpaper#31]
The real sunrise is in the east and sunset in the west. This makes the sun to move to the right. In the image the sun moves to the left. One way to hotfix this is to mirror each image. Here a video as reference: [https://www.youtube.com/watch?v=ylLqqI7A1Gg](https://www.youtube.com/watch?v=ylLqqI7A1Gg)

**Comment by adi1090x** [comment]
Noted!
