### ISSUE TITLE
Combining with pywal?

### ISSUE THREAD

**Issue by samsa283** [adi1090x/dynamic-wallpaper#34]
Hi,
I really would like to combine your script with Pywal [https://github.com/dylanaraps/pywal](url). So that every hour the terminal color scheme would also change. That would be so cool. I do not have any coding ablities, so I really dont know how to even begin. Do you have any suggestions?

edit: The link does not work for me properly. Please google https://github.com/dylanaraps/pywal

**Comment by das-s** [comment]
As far as I'm aware this is not really possible in the current state. I'm currently testing a [fork](https://github.com/das-s/dynamic-wallpaper) where the path of the currently used wallpaper is written into a cache file. That path could be fed into pywal. You'd still need to run dwall via cron job though to get hourly updates. 

To achieve this functionality get the aforementioned fork from github and make the dwall script in that repo executable. Copy paste the following script into a file and place it somewhere in your home dir (e.g. `/home/samsa283/bin/my-script.sh`):
```
#!/usr/bin/env bash
export DISPLAY=:0 # This is ensuring the display is properly set
/path/to/dwall-script -o firewatch3 & wal --backend wal -i "$(cat ~/.cache/dwall/currentimage)"
```
Change the path for the dwall script (the forked one) and make the new script executable with `chmod +x /home/samsa283/bin/my-script.sh`. Install a cron job utility then use `crontab -e` to insert the following:
```
0 * * * * /home/samsa283/bin/my-script.sh
```
You can test it if its working properly by replacing the `0 * * * *` with `* * * * *` to make it run on every minute (Have a look at the [arch wiki](https://wiki.archlinux.org/index.php/Cron)).

Hope that helps.

**Comment by hixan** [comment]
I ended up creating my own script that will change wallpapers according to the time in python and calling pywal from that script (with some checks to make sure the process doesnt get started multiple times) I can share if there is any interest

**Comment by adi1090x** [comment]
Done.

**Comment by pnchinmay** [comment]
> I ended up creating my own script that will change wallpapers according to the time in python and calling pywal from that script (with some checks to make sure the process doesnt get started multiple times) I can share if there is any interest

Hi @hixan, could you share your script ?

**Comment by pnchinmay** [comment]
Nevermind, found the file `~/.cache/dwall_current`
