### ISSUE TITLE
Using the 'memory' GSettings backend.

### ISSUE THREAD

**Issue by pozharus** [adi1090x/dynamic-wallpaper#36]
Try: dwall -s forest or dwall -o forest
And have message:  Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

Resulf of 'echo $DESKTOP_SESSION' : 'ubuntu'.
 
App was install using guide from main page. (xserver, then repository)
Thanks for something helping.

**Comment by adi1090x** [comment]
Try the new version.
