### ISSUE TITLE
Editing the Time of wallpaper change

### ISSUE THREAD

**Issue by prajul-L850** [adi1090x/dynamic-wallpaper#38]
Hello,I'm using the style firewatch3(or firewatch alt),which only has 2 wallpapers. I would like the night wallpaper to turn on at 7:30 P.M. Is there any way to edit the time?

**Comment by prajul-L850** [comment]
![Screenshot from 2020-10-27 19 03 23](https://user-images.githubusercontent.com/69051313/97308682-26784580-1887-11eb-942b-1762584e038a.png)

**Comment by adi1090x** [comment]
depends on how you create a cronjob.
