### ISSUE TITLE
Wallpaper don't changing on cinnamon

### ISSUE THREAD

**Issue by ramazanemreosmanoglu** [adi1090x/dynamic-wallpaper#42]
Hi;

I am using fedora 33 with cinnamon desktop, but wallpaper dont changing.

https://unix.stackexchange.com/questions/59653/change-desktop-wallpaper-from-terminal

Can we use this solution?

**EDIT:** I solved, I'm, creating a pull request now. https://github.com/adi1090x/dynamic-wallpaper/pull/43

**Comment by adi1090x** [comment]
Thanks...
