### ISSUE TITLE
dwall says pywal isn't installed even if it is

### ISSUE THREAD

**Issue by Lanhild** [adi1090x/dynamic-wallpaper#47]
`~$dwall -s lakeside &`
`[1] 42971`
`~$ [*] Using style : lakeside
[!] pywal is not installed on your system, exiting..`
`~$ echo $DESKTOP_SESSION`
`xubuntu`

`~$ pip3 install pywal`
`Requirement already satisfied: pywal in ./.local/lib/python3.8/site-packages (3.3.0)`

@adi1090x

**Comment by Sagyam** [comment]
Pywal being not optional even though docs say it's  optional  is the root cause of most of our issues.
Apparently [this](https://github.com/adi1090x/dynamic-wallpaper/pull/48/commits/6524b29074689a74408a3f34ad07c3e9643e2106) PR claims to fix the pywal bug.
Looks like we will just have to wait.

**Comment by Sagyam** [comment]
Try add environment variable  **PATH** to your cron file.
Run echo `$PATH`
Update cron file with
```
0 * * * * env PATH=<your-path> DISPLAY=:0 DESKTOP_SESSION=/usr/share/xsessions/plasma DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" /usr/bin/dwall -s lakeside
```

**Comment by Lanhild** [comment]
nope, doesn't work.

**Comment by Sagyam** [comment]
What's the error message this time?

**Comment by Lanhild** [comment]
The exact same

**Comment by adi1090x** [comment]
Try again, I've fixed it.

**Comment by Vepnar** [comment]
You could try installing pywall with super user.
`sudo pip3 install pywal`
This solved the issue for me.

**Comment by Lanhild** [comment]
> You could try installing pywal with super user.
> `sudo pip3 install pywal`
> This solved the issue for me.

It solved it, thanks!
