### ISSUE TITLE
dwall change lockscreen wallpaper[kde neon]

### ISSUE THREAD

**Issue by 1999shaswat** [adi1090x/dynamic-wallpaper#49]
(base) shade@shade-HP-ProBook-450-G1:~$ echo "$SHELL | $DISPLAY | $DESKTOP_SESSION | $DBUS_SESSION_BUS_ADDRESS | $XDG_RUNTIME_DIR"
/bin/bash | :0 | /usr/share/xsessions/plasma | unix:path=/run/user/1000/bus | /run/user/1000

(base) shade@shade-HP-ProBook-450-G1:~$ crontab -l
0 * * * * env DISPLAY=:0 DESKTOP_SESSION=/usr/share/xsessions/plasma DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" /usr/bin/dwall -s room

I have tested cronjob and it works.
running dwall directly works but from cronjob doesn't. Why?

**Comment by Sagyam** [comment]
[Same](https://github.com/adi1090x/dynamic-wallpaper/issues/45) problem here.
If you check this logs of it may say `pywal is not installed on your system, exiting...` even though  pip3 list show pywall as already installed.

**Comment by Sagyam** [comment]
Try add environment variable  **PATH** to your cron file.
Run echo `$PATH`
Update cron file with
```
0 * * * * env PATH=<your-path> DISPLAY=:0 DESKTOP_SESSION=/usr/share/xsessions/plasma DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" /usr/bin/dwall -s room
```

**Comment by 1999shaswat** [comment]
> Try add environment variable **PATH** to your cron file.
> Run echo `$PATH`
> Update cron file with
> 
> ```
> 0 * * * * env PATH=<your-path> DISPLAY=:0 DESKTOP_SESSION=/usr/share/xsessions/plasma DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" /usr/bin/dwall -s room
> ```

Thanks a lot. Was just going through your issue. Followed it and now it works!
