### ISSUE TITLE
permission denied on jpgs

### ISSUE THREAD

**Issue by thedaemon** [adi1090x/dynamic-wallpaper#57]
I get this issue every style tested. Here are a few
/usr/bin/dwall: line 171: /usr/share/dynamic-wallpaper/images/forest/21.jpg: Permission denied
/usr/bin/dwall: line 171: /usr/share/dynamic-wallpaper/images/moon/22.jpg: Permission denied
/usr/bin/dwall: line 171: /usr/share/dynamic-wallpaper/images/market/22.jpg: Permission denied

**Comment by adi1090x** [comment]
Make sure you've permission to access files in /usr/share dir.

**Comment by thedaemon** [comment]
My permissions are fine.

❯ ls -l /usr/share/dynamic-wallpaper/images/moon/22.jpg 
-rw-r--r--  1 root  wheel   146K Jan  5 21:59 /usr/share/dynamic-wallpaper/images/moon/22.jpg

**Comment by adi1090x** [comment]
Try the new version.

**Comment by eyeaxamsterdam** [comment]
This is my problem as well. I changed the dwall.sh script to point to /home/images because this has permissions for my user. but still hitting the same permission problems. I got this working years ago quickly a lot has changed with gnome since then. Wish I could figure it out.

**Comment by eyeaxamsterdam** [comment]
example of cron output 

/home/deadbones/dynamic-wallpaper/dwall.sh: line 194: /home/deadbones/dynamic-wallpaper/images/firewatch/13.png: Permission denied
