### ISSUE TITLE
Cron Job Instructions for Debian

### ISSUE THREAD

**Issue by gesteves91** [adi1090x/dynamic-wallpaper#60]
First of all, I would like to say that I loved this project. Thanks a lot for developing it. However, I have one question for the developers, would you guys bother to add installation instructions about the cron job for the Debian based distros (such as Ubuntu) in the README.

**Comment by GitGangGuy** [comment]
Hi @gesteves91,
it appears that @adi1090x has abandoned this project (the last commit was in January), but I have continued development in my fork [Dynamic Wallpaper Improved](https://github.com/GitGangGuy/dynamic-wallpaper-improved). Feel free to open your issue there so I can take a look at it!

**Comment by adi1090x** [comment]
@gesteves91 , maybe he didn't... He is an Indian and by judging the current condition of india, he may be really really sick, you know... Maybe he's on the bed, with a mask on his nose.

Anyway, good work, keep it up... I'll resume this stuff, If I'm not dead.

**Comment by GitGangGuy** [comment]
@adi1090x I hope everything is well with you in India (or at least going to be soon)! 😷 
I did not mean to pressure you into doing anything regardless of your current condition, but simply to redirect issues to my fork - You don't have to pick the project up again if you don't want to, that's what the FOSS community is about! 😄 
Anyway, I hope you'll get better real soon 😇

**Comment by gesteves91** [comment]
Thanks @GitGangGuy for the suggestion. I am going to take a look at your fork
@adi1090x I hope you are doing all right down there
About this issue, I actually found a solution to install in Debian-based distros. I only needed to use the command `sudo systemctl enable cron`, and the rest of the tutorial works great from there
Again it would be nice to have it in the README, but it is not really an issue
Thanks guys

**Comment by dhollinger** [comment]
Any particular reason someone couldn't use `systemd-timer` instead of cron?

**Comment by adi1090x** [comment]
very much subjective, as long as you create a job to do the thing.
