### ISSUE TITLE
Wallpaper not changing

### ISSUE THREAD

**Issue by vitorfrois** [adi1090x/dynamic-wallpaper#62]
Good morning! I'm new to linux. Tried to install DWall but the wallpapers arent changing. My OS is Ubuntu.
How can I solve this problem?
![Screenshot from 2021-01-14 09-06-21](https://user-images.githubusercontent.com/46361092/104588893-d28c2a00-5647-11eb-90d5-c9e66985cac1.png)

**Comment by Sagyam** [comment]
Can you provide more info?
Try running `neofetch`.
Do wallpaper change when done manually?

**Comment by adi1090x** [comment]
Use the latest version (`v3.0`)
