### ISSUE TITLE
Add the dwall command corresponding to our theme in .bashrc

### ISSUE THREAD

**Issue by utarasama** [adi1090x/dynamic-wallpaper#63]
When I go to sleep, I shutdown my computer when the wallpaper is in night theme. When I wake up, I want to have the day theme, and not have to wait an hour to see the modification.

So, I recommand to add this command to the `~/.bashrc` file :
```
dwall -s <my-theme>
```

This doesn't affect our cron. But, if we edit it to change the theme, we have to edit the `~/.bashrc` file in consequence, with the new theme chosen. So, I suggest to edit the documentation :)

**Comment by GitGangGuy** [comment]
Hi @mehdi60,
it appears that @adi1090x has abandoned this project (the last commit was in January), but I have continued development in my fork [Dynamic Wallpaper Improved](https://github.com/GitGangGuy/dynamic-wallpaper-improved). Feel free to open your issue there so I can take a look at it!

**Comment by adi1090x** [comment]
Done.
