### ISSUE TITLE
wallpaper not changing with pop!_os on system76 laptop

### ISSUE THREAD

**Issue by iceman42** [adi1090x/dynamic-wallpaper#67]
Wallpaper doesn't change, with cron or with the command `dwall -s <style>` for all styles on a system76 laptop running pop!_os with the cinnamon desktop environment.

Output of `echo $DESKTOP_SESSION` is `cinnamon`

Weirdly, on pop!_os installed on an old hp laptop it works fine.
Thanks

**Comment by tomturbu** [comment]
Hi,
seems like my issue - i've also posted here an issue plus a workaround...
You can check if my workaround works -> https://github.com/adi1090x/dynamic-wallpaper/issues/64

best,
Thomas

**Comment by GitGangGuy** [comment]
Hi @iceman42,
it appears that @adi1090x has abandoned this project (the last commit was in January), but I have continued development in my fork [Dynamic Wallpaper Improved](https://github.com/GitGangGuy/dynamic-wallpaper-improved). Feel free to open your issue there so I can take a look at it!

**Comment by iceman42** [comment]
Hi @tomturbo,
Thanks for your reply. I've actually stopped using pop! for the moment, was in a bit of distro-hopping phase but have settled on something different now. 
I'm not sure your workaround would help any future pop! users that face the same problem: if I understand correctly, you're trying to change system colours and the background? And you do this by changing the background first, then doing both? My issue was that even just changing the background on its own wouldn't work. Unfortunately I've uninstalled pop!, so can't check.
Thanks anyway,
iceman

**Comment by Bluqui** [comment]
I can to check :D

![image](https://user-images.githubusercontent.com/63772059/128206502-d1ab418e-7e13-41c5-91ee-26993d04e10d.png)

As you can see... the wallpapaer pops up when i type the command
But it doesnt change with the time

![image](https://user-images.githubusercontent.com/63772059/128206953-e03951e2-9c8b-4f58-8329-d9e75ba93800.png)

"pop"

![image](https://user-images.githubusercontent.com/63772059/128207656-28b88566-f3e7-4303-9610-85fec91bb302.png)

What is that?

**Comment by gesteves91** [comment]
Hi @Bluqui, have you found any workarounds? I also use POP, and I am facing the same problem now

**Comment by ch0chi** [comment]
Hey there, I know this is old, but I figured I'd update this in case anyone else needs help.
I got this working on Pop_OS! by simply setting `DESKTOP_SESSION` to `gnome`.
When you run `echo $DESKTOP_SESSION` in pop os, it outputs `pop`. However, Pop OS uses gnome as its default display manager. So, setting `DESKTOP_SESSION="gnome"` should fix the issue for you.

**Comment by Bluqui** [comment]
thanks for you post `:D`
i'll try it

**Comment by Bluqui** [comment]
> Hey there, I know this is old, but I figured I'd update this in case anyone else needs help. I got this working on Pop_OS! by simply setting `DESKTOP_SESSION` to `gnome`. When you run `echo $DESKTOP_SESSION` in pop os, it outputs `pop`. However, Pop OS uses gnome as its default display manager. So, setting `DESKTOP_SESSION="gnome"` should fix the issue for you.

Looks like doenst work :(

**Comment by Bluqui** [comment]
> > Hey there, I know this is old, but I figured I'd update this in case anyone else needs help. I got this working on Pop_OS! by simply setting `DESKTOP_SESSION` to `gnome`. When you run `echo $DESKTOP_SESSION` in pop os, it outputs `pop`. However, Pop OS uses gnome as its default display manager. So, setting `DESKTOP_SESSION="gnome"` should fix the issue for you.
> 
> Looks like doenst work :(

Maybe... i made a bad crontab file?

**Comment by adi1090x** [comment]
Use the lastest version (`v3.0`) and see if it solve your issue.
