### ISSUE TITLE
Script fails in zsh

### ISSUE THREAD

**Issue by corfeur12** [adi1090x/dynamic-wallpaper#7]
I assume this is because of the $SETTER not being expanded which could be fixed by adding the line `set -o shwordsplit 2>/dev/null` to the top of the script(s)

As seen in [Pull #8](https://github.com/adi1090x/dynamic-wallpaper/pull/8)

**Comment by BerentM** [comment]
I'm using zsh and trying to run: `dwall -s=firewatch`
It outputs:
>  Image 18.jpg/.png Not Available, Exiting...

Did you get similar error message?

**Comment by corfeur12** [comment]
@BerentM if you are using the Gnome desktop then this is likely due to the gsettings command not returning an error value. If you checkout and merge [Pull #6](https://github.com/adi1090x/dynamic-wallpaper/pull/6) and [Pull #8](https://github.com/adi1090x/dynamic-wallpaper/pull/8) then that will fix any Gnome issues. If you pull [my fork](https://github.com/corfeur12/dynamic-wallpaper) then both of these changes have already been applied, but I will not be updating my fork as this one updates so you won't get any new features.

Other possible issues could be:

- you didn't run the install.sh script so the dwall is searching in the wrong directory
- the script is being called before a graphical environment has loaded. I had an issue with this when I tried to run the script as a startup application rather than just adding `dwall -s=firewatch2 &` to my .profile

**Comment by adi1090x** [comment]
fixed many issues, pls try again.
