### ISSUE TITLE
Development continues in my fork 'Dynamic Wallpaper Improved'!

### ISSUE THREAD

**Issue by ghost** [adi1090x/dynamic-wallpaper#71]
Hi all,
it appears that @adi1090x has abandoned this project (the last commit was in January), so I added a few features to dwall I urgently needed in [my own fork](https://github.com/GitGangGuy/dynamic-wallpaper-improved). I will continue developing there, so feel free to join in on the fun! I'll try to address any issues that come up and I'm looking forward to merging your PRs!
:partying_face:

**Comment by adi1090x** [comment]
404
