### ISSUE TITLE
invalid image file

### ISSUE THREAD

**Issue by ryawann** [adi1090x/dynamic-wallpaper#72]
so i downloaded heic files from the website, converted them to jpgs, renamed them "0"-"7" and put them in their own folder. how come when i try and set them as the wallpaper i get an "invalid image file" error?

**Comment by ryawann** [comment]
oh and i forgot to mention im using fedora

**Comment by BrianRuizy** [comment]
@ryawann I believe you need to number 0-23 for all hours of the day

**Comment by adi1090x** [comment]
make 24 files, read the instructions on readme.
