### ISSUE TITLE
Change wallpapers every 15 minutes

### ISSUE THREAD

**Issue by AshutoshFreak** [adi1090x/dynamic-wallpaper#77]
I have a set of 96 wallpapers (numbered from 0-95) taken from [here](https://dynamicwallpaper.club/wallpaper/qvvk60oi7v). How do I change my wallpaper every 15 minutes?

**Comment by andremeireles** [comment]
On file `test.sh`, line 16, change `HOUR='date +%k'`.
The expression needs to be something like ((hour * 60) + minutes) / 15)
**HOUR** is `date +%k`
**MINUTES** is `date +%M`
Make sure the result is a integer and not a float number.

**Comment by adi1090x** [comment]
Seems like solved, modify the script accordingly.
