### ISSUE TITLE
Will there be a version of this for any other distros than Arch(-based)/Ubuntu(-based) and Debian(-based) ones?

### ISSUE THREAD

**Issue by VNGamerGit** [adi1090x/dynamic-wallpaper#88]
Question above, I'm going to switch to Gentoo, but it seems like there's no installation guide for it, nor is there any installation guides for any other distros than Arch(-based)/Ubuntu(-based) and Debian(-based) ones. Can I build the whole thing from source, then install it?

**Comment by adi1090x** [comment]
It will work on any Linux OS as long as you install all the required programs.
