### ISSUE TITLE
Why isn't the wallpaper watching the time? ~$ echo $DESKTOP_SESSION pantheon

### ISSUE THREAD

**Issue by tusharhero** [adi1090x/dynamic-wallpaper#89]
![image](https://user-images.githubusercontent.com/54012021/155759213-f022b6d6-b892-4ce0-9612-307830b12d95.png)

**Comment by tusharhero** [comment]
As you can see it is almost 11pm and I can still see the sun's light.

**Comment by dtrunk90** [comment]
Did you even set up a cronjob?
