### ISSUE TITLE
KDE support

### ISSUE THREAD

**Issue by fcanela** [adi1090x/dynamic-wallpaper#9]
Hello! I love the concept. What is preventing it from working with KDE? As KDE user, is there something I can consider contributing?

Thanks.

**Comment by adi1090x** [comment]
I'm trying to understand the wallpaper setting mechanism on kde, it's a bit complicated for me yet. you have any idea?
also maybe you can show me the output of `echo $DESKTOP_SESSION`

**Comment by fcanela** [comment]
```
$ echo $DESKTOP_SESSION
plasma
```

After searching on the internet, I was able to programatically change all my monitors wallpapers using this:

```
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///home/fcanela/media/images/wallpapers/test.jpg")}'
```

It is a huge line, but easy to parametrize: We only have to change `/home/fcanela/media/images/wallpapers/test.jpg` for our wallpaper test.

This changes the wallpaper in all the Activities, so it would be nice to warn the users about it.

How do you feel regarding this? Can I try to push a PR if I find time for it?
I have

**Comment by adi1090x** [comment]
I've added KDE support. tested it on KDE NEON and it's working.
please try and let me know if it's working for you.

**Comment by fcanela** [comment]
That was fast :rocket: I will try during today and confirm. Thanks!

**Comment by fcanela** [comment]
It seems to be working fine. Wow, you had it solved like 6 hours after I opened the issue.

Thanks! I will tell if I find any problem, but so far it is working flawless.
