### ISSUE TITLE
Wallpaper not changing after Pop OS upgrade

### ISSUE THREAD

**Issue by GabrielN11** [adi1090x/dynamic-wallpaper#92]
echo $DESKTOP_SESSION
pop

**Comment by BrendanParmer** [comment]
I think it has to do with GNOME's new setting to switch wallpapers based on light or dark mode. If you're using dark mode, you can modify the dwall.sh script, changing line 131 from
```SETTER="gsettings set org.gnome.desktop.background picture-uri"```
to
```SETTER="gsettings set org.gnome.desktop.background picture-uri-dark"```

**Comment by GabrielN11** [comment]
Hey, thanks for your answer. I reinstalled dwall and changed the line like you said and it works now, Thank you again :)

**Comment by lucas-bernardino** [comment]
I was having the same issue. I changed the dwall.sh, installed it again but got a new error. So I changed back to the original script and installed it again and now suddenly it works perfectly. Thanks nevertheless.

**Comment by trev-infostrux** [comment]
> I think it has to do with GNOME's new setting to switch wallpapers based on light or dark mode. If you're using dark mode, you can modify the dwall.sh script, changing line 131 from `SETTER="gsettings set org.gnome.desktop.background picture-uri"` to `SETTER="gsettings set org.gnome.desktop.background picture-uri-dark"`

for me on pop in November 6th 2024 , it was originally this:
`## Set wallpaper in GNOME
 set_gnome() {
     gsettings set org.gnome.desktop.background picture-uri "file:///$1"
     gsettings set org.gnome.desktop.screensaver picture-uri "file:///$1"
 }
`

I changed it to 
`## Set wallpaper in GNOME
 set_gnome() {
     gsettings set org.gnome.desktop.background picture-uri-dark "file:///$1"
     gsettings set org.gnome.desktop.screensaver picture-uri "file:///$1"
 }
`

note the change is only adding -dark on the first line
