### ISSUE TITLE
Invalid style of all default implemented styles

### ISSUE THREAD

**Issue by rilysh** [adi1090x/dynamic-wallpaper#95]
Am I doing anything wrong? I've tried to use styles but it's keep saying that style not found. I'm on Debian 11 with XFCE.DE.

![image](https://user-images.githubusercontent.com/71683721/171555207-525a4ded-6ebf-4a28-a4d4-55cb5f9e93a6.png)

I've tried with other styles as well, doesn't seems like it will going to work for me.

**Comment by adi1090x** [comment]
Use the lastest version (`v3.0`)
