### ISSUE TITLE
How to use this with Archcraft Wayfire?

### ISSUE THREAD

**Issue by aksalsf** [adi1090x/dynamic-wallpaper#99]
I'm figuring out to use this app with Archcraft Wayfire. I've installed it before, but it seems doesn't works. Is it because of wallpaper settings on Wayfire configuration?

**Comment by victorbnl** [comment]
Did you try the test script? Does it work?

**Comment by aksalsf** [comment]
> Did you try the test script? Does it work?

I've tried before, there's no issue when running the script. But, the wallpaper still didn't change, even I restarting my desktop. I'm still figuring out what's the problem.

Should I change the wayfire.ini configuration maybe?
![image](https://user-images.githubusercontent.com/43602616/187064021-83cf865b-5a29-4c28-884c-7c13500f7610.png)

**Comment by victorbnl** [comment]
Do you have feh ? Does `feh --bg-scale an_image.(jpg|png)` set your wallpaper correctly?

**Comment by victorbnl** [comment]
Also does dwall throw an error?

**Comment by adi1090x** [comment]
Fixed and tested, Use the lastest version (`v3.0`)
